sonar.projectKey=${{ secrets.SONARQUBE_PROJECT_KEY }} \
sonar.host.url=${{ secrets.SONARQUBE_URL }} \
sonar.login=${{ secrets.SONAR_TOKEN }}

sonar.sources=src
sonar.projectBaseDir=.
sonar.sourceEncoding=UTF-8